stages:          # List of stages for jobs, and their order of execution
  - deploy

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* build stages complete successfully.
  script:
    - echo "Deploying application..."
    - docker compose up -d
    - echo "Application successfully deployed."