version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./api/src/main/resources/db/migration:/docker-entrypoint-initdb.d
  etherpad:
    image: etherpad/etherpad:latest
    restart: always
    platform: linux/amd64
    hostname: etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    platform: linux/amd64
    ports:
      - "2525:25"
  back:
    image: back
    build:
      context: api
      dockerfile: ./Dockerfile
    environment: 
      - quarkus.datasource.jdbc.url=jdbc:mysql://db:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
      - doodle.internalPadUrl=http://etherpad:9001/ 
      - doodle.externalPadUrl=http://pad.tlc.fr/
    hostname: back
    depends_on:
      db:
        condition: service_healthy
      mail: 
        condition : service_started
      etherpad:
        condition : service_started
    expose:
      - "8080:8080"
  front:
    build:
      context: front
      dockerfile: ./Dockerfile
    hostname: front
    image: front
    ports:
      - "80:80"
    depends_on:
      - back
    volumes:
      - ./front/default.conf:/etc/nginx/conf.d/default.conf